#!/bin/bash

# This is run after the build

echo "++++ Deploy ++++"

echo "export OPENSHIFT_NODEJS_PATH_ELEMENT=${OPENSHIFT_REPO_DIR}node_modules/.bin:$OPENSHIFT_NODEJS_PATH_ELEMENT"
export OPENSHIFT_NODEJS_PATH_ELEMENT=${OPENSHIFT_REPO_DIR}node_modules/.bin:$OPENSHIFT_NODEJS_PATH_ELEMENT
