#!/bin/bash

# This is run after the build

COFFEE_BIN_DST="${HOME}.node_modules/.bin"
COFFEE_BIN_SRC="${OPENSHIFT_REPO_DIR}node_modules/.bin/coffee"

echo "++++ Deploy ++++"
cd $COFFEE_BIN_DST
ln -s $COFFEE_BIN_SRC .
echo "ln -s $COFFEE_BIN_SRC $COFFEE_BIN_DST"
