#!/bin/bash

# This is sort of a hack since I can't seem to change how the default node.js
# cartridge invokes the 'supervisor' start script.

echo "++++ Pre-Build ++++"
#npm install -g coffee-script@1.7.1 # don't have permissions here.
