#!/bin/bash

LOG_FILE=/dev/null
APP_FILE=server.coffee
PROC=node_modules/.bin/coffee
WATCH_DIR='.'

# Use supervisor to keep node app running after crash
echo "nohup supervisor  -w $WATCH_DIR -x $PROC $APP_FILE >$LOG_FILE 2>&1 &"
nohup supervisor -w $WATCH_DIR -x $PROC $APP_FILE >$LOG_FILE 2>&1 &
